### PR TITLE
Tutorial updated

### PR DESCRIPTION
**Pull request by shingenmochi**
## Add `Data preparation` section.

- Indicate the requirements of Tomo-seq data.
- Post an example of Tomo-seq data using `tomoseq_test_x`.

## Misc
- Update example figure.

### CODE REVIEW

**Review by yuifu — CHANGES_REQUESTED** [review]
- Please replace the word "segment(s)" with "section(s)"
- "It is a `data.frame` object." -> "It is a `data.frame` object for each axis"
- Add the requiarement "1. The order of the second and subsequent columns should be the same as the order of the sections"
- In Data example, segment1, 2, 3... should be section1, 2, 3... (for consistency of terminology)

**Comment by yuifu** [comment]
@shingenmochi I submitted some feedbacks!

**Comment by shingenmochi** [comment]
I finished modification!

**Review by yuifu — APPROVED** [review]

**Comment by yuifu** [comment]
Thanks!

**Pull request merged**
