### PR TITLE
Add error messages

### PR DESCRIPTION
**Pull request by shingenmochi**
Added some error messages about
- invalid class
- geneID not found
- have not reconstructed expression yet

### CODE REVIEW

**Review by yuifu — CHANGES_REQUESTED** [review]
> "rectangle", "round" or "halfround" 

This specification should also be written in doc. (line 13)

**Review by yuifu — CHANGES_REQUESTED** [review]
> 1st parameter must be tomoSeq class object.

should be

"First argument must be tomoSeq class object."

**Review by yuifu — CHANGES_REQUESTED** [review]
> "No result of reconstruction."

should be

"No reconstructed results."

> "You need to run Estimate3dExpressions()"

shoud be

"You need to run Estimate3dExpressions() first."

**Comment by yuifu** [comment]
Sorry, please ignore this comment:


```
> "You need to run Estimate3dExpressions()"

shoud be

"You need to run Estimate3dExpressions() first."
```

**Comment by shingenmochi** [comment]
The fix is completed.
- reflect change requests
- fixed bug
    - in Estimate3dExpressions, error checking doesn't work correctly when `query` has multiple geneIDs

**Review by yuifu — APPROVED** [review]

**Pull request merged**
